---
- hosts: fortigates
  collections:
   - fortinet.fortios
  vars:
   vdom: "root"
   host: "192.168.10.200"
   username: "admin"
   password: "fortinet"
   ssl_verify: "False"
  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      vdom:  "{{ vdom }}"
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: "False"
      system_global:
        hostname: "FortiGate02"
