---

- name: "test"
  hosts: test-fgt
  collections:
  - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
  tasks:
  - name: Configure global attributes.
    fortios_system_global:
      vdom:  "{{ vdom }}"
      system_global:
        hostname: "FortiGate02"
