---

- name: "test"
  hosts: test-fgt
  collections:
  - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
  tasks:
  - name: Get managed Access-Points
    fortios_configuration_fact:
        selectors:
          - selector: wireless-controller_wtp
          - selector: wireless-controller_vap
