---

- name: "test"
  hosts: test-fgt
  collections:
  - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
  vars_promt:
  - name: nat_needed
    prompt: Is NAT needed [yes;no]?
    private: no
    default: no
  tasks:
  - name: Get managed Access-Points
    fortios_configuration_fact:
        selectors:
          - selector: wireless-controller_wtp-status
    register: managed_ap
  - name: Write Output
    debug:
      msg: "Folgende APs: {{ managed_ap }}"
